"""empty message

Revision ID: 1092f1c3e3a6
Revises: ecb495847e68
Create Date: 2019-05-19 22:39:10.687235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1092f1c3e3a6'
down_revision = 'ecb495847e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignedcenter', sa.Column('center_public_id', sa.String(length=300), nullable=False))
    op.create_unique_constraint(None, 'distcenter', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'distcenter', type_='unique')
    op.drop_column('assignedcenter', 'center_public_id')
    # ### end Alembic commands ###
