"""empty message

Revision ID: 21e1e46a47f6
Revises: b590450491b1
Create Date: 2019-05-20 10:27:16.361757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e1e46a47f6'
down_revision = 'b590450491b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependents', sa.Column('home_id', sa.Integer(), nullable=True))
    op.drop_constraint('dependents_homeOwner_id_fkey', 'dependents', type_='foreignkey')
    op.create_foreign_key(None, 'dependents', 'evacuees', ['home_id'], ['id'])
    op.drop_column('dependents', 'homeOwner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependents', sa.Column('homeOwner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dependents', type_='foreignkey')
    op.create_foreign_key('dependents_homeOwner_id_fkey', 'dependents', 'evacuees', ['homeOwner_id'], ['id'])
    op.drop_column('dependents', 'home_id')
    # ### end Alembic commands ###
