"""empty message

Revision ID: 294340629888
Revises: f29277abb93f
Create Date: 2020-01-16 19:05:36.333247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294340629888'
down_revision = 'f29277abb93f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('role_id', sa.Integer(), nullable=True))
    op.drop_constraint('account_role_fkey', 'account', type_='foreignkey')
    op.create_foreign_key(None, 'account', 'role', ['role_id'], ['id'])
    op.drop_column('account', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.create_foreign_key('account_role_fkey', 'account', 'role', ['role'], ['id'])
    op.drop_column('account', 'role_id')
    # ### end Alembic commands ###
