"""empty message

Revision ID: 35939dc10c2e
Revises: dc39a0f54d07
Create Date: 2019-04-26 12:31:49.670000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35939dc10c2e'
down_revision = 'dc39a0f54d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dependents_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('gender', sa.String(length=300), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('educ_attainment', sa.String(length=300), nullable=False),
    sa.Column('occupation', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['address'], ['evacuees.address'], ),
    sa.PrimaryKeyConstraint('id', 'dependents_id')
    )
    op.add_column(u'evacuees', sa.Column('dependents_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'evacuees', 'dependents', ['dependents_id'], ['dependents_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evacuees', type_='foreignkey')
    op.drop_column(u'evacuees', 'dependents_id')
    op.drop_table('dependents')
    # ### end Alembic commands ###
