"""empty message

Revision ID: 3a31e09433d3
Revises: 4e2ff13845ab
Create Date: 2019-04-23 19:17:57.310131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a31e09433d3'
down_revision = '4e2ff13845ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distcenter', sa.Column('publicid', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distcenter', 'publicid')
    # ### end Alembic commands ###
