"""empty message

Revision ID: 3a8751b7d495
Revises: 21e1e46a47f6
Create Date: 2019-05-20 10:48:19.959890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8751b7d495'
down_revision = '21e1e46a47f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignedcenter', sa.Column('evacuees_id', sa.Integer(), nullable=True))
    op.drop_constraint('assignedcenter_dependents_id_fkey', 'assignedcenter', type_='foreignkey')
    op.create_foreign_key(None, 'assignedcenter', 'evacuees', ['evacuees_id'], ['id'])
    op.drop_column('assignedcenter', 'dependents_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignedcenter', sa.Column('dependents_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assignedcenter', type_='foreignkey')
    op.create_foreign_key('assignedcenter_dependents_id_fkey', 'assignedcenter', 'dependents', ['dependents_id'], ['id'])
    op.drop_column('assignedcenter', 'evacuees_id')
    # ### end Alembic commands ###
