"""empty message

Revision ID: 3e799fa51b38
Revises: 51d7fd829968
Create Date: 2019-08-07 10:57:40.345260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e799fa51b38'
down_revision = '51d7fd829968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.String(length=100), nullable=True),
    sa.Column('received_date', sa.String(length=300), nullable=False),
    sa.Column('received_from', sa.String(length=300), nullable=False),
    sa.Column('distribute_date', sa.String(length=300), nullable=True),
    sa.Column('expiry', sa.String(length=300), nullable=True),
    sa.Column('size', sa.String(length=5), nullable=False),
    sa.Column('clothing_type', sa.String(length=300), nullable=False),
    sa.Column('condition', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['distcenter.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    # ### end Alembic commands ###
