"""empty message

Revision ID: 45e3358b6dfa
Revises: 9be62c0869cd
Create Date: 2019-05-19 22:32:18.922576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e3358b6dfa'
down_revision = '9be62c0869cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignedcenter', sa.Column('center_public_id', sa.String(length=300), nullable=True))
    op.create_foreign_key(None, 'assignedcenter', 'distcenter', ['center_public_id'], ['public_id'])
    op.create_unique_constraint(None, 'distcenter', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'distcenter', type_='unique')
    op.drop_constraint(None, 'assignedcenter', type_='foreignkey')
    op.drop_column('assignedcenter', 'center_public_id')
    # ### end Alembic commands ###
