"""empty message

Revision ID: 4b886a57ab26
Revises: 4db030c35ea2
Create Date: 2019-05-19 17:33:35.291205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b886a57ab26'
down_revision = '4db030c35ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distcenter', 'marker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distcenter', sa.Column('marker', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
