"""empty message

Revision ID: 54d56abf62e9
Revises: b6772b5be048
Create Date: 2019-05-17 11:26:13.279589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d56abf62e9'
down_revision = 'b6772b5be048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('left_id', sa.String(length=100), nullable=True),
    sa.Column('right_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['useradmin.public_id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['distcenter.public_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    # ### end Alembic commands ###
