"""empty message

Revision ID: 6164691c68b4
Revises: a5850917324f
Create Date: 2019-04-27 01:25:58.299308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6164691c68b4'
down_revision = 'a5850917324f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distcenter', sa.Column('public_id', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distcenter', 'public_id')
    # ### end Alembic commands ###
