"""empty message

Revision ID: 7bc080bd6b4c
Revises: 9c4d48dcfec9
Create Date: 2019-05-17 14:00:58.864342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc080bd6b4c'
down_revision = '9c4d48dcfec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('center_manage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.String(length=100), nullable=True),
    sa.Column('center_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['useradmin.public_id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['distcenter.public_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('left_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('right_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['useradmin.public_id'], name='association_left_id_fkey'),
    sa.ForeignKeyConstraint(['right_id'], ['distcenter.public_id'], name='association_right_id_fkey')
    )
    op.drop_table('center_manage')
    # ### end Alembic commands ###
