"""empty message

Revision ID: 9be62c0869cd
Revises: b3b39523685d
Create Date: 2019-05-19 22:26:16.721046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be62c0869cd'
down_revision = 'b3b39523685d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignedcenter', sa.Column('center_public_id', sa.String(length=300), nullable=True))
    op.create_foreign_key(None, 'assignedcenter', 'distcenter', ['center_public_id'], ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignedcenter', type_='foreignkey')
    op.drop_column('assignedcenter', 'center_public_id')
    # ### end Alembic commands ###
