"""empty message

Revision ID: a3887094e1b1
Revises: 4b886a57ab26
Create Date: 2019-05-19 22:05:50.858952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3887094e1b1'
down_revision = '4b886a57ab26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignedcenter',
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('center_admin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['center_admin'], ['useradmin.username'], ),
    sa.PrimaryKeyConstraint('center_id')
    )
    op.add_column('distcenter', sa.Column('useradmin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'distcenter', 'useradmin', ['useradmin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'distcenter', type_='foreignkey')
    op.drop_column('distcenter', 'useradmin_id')
    op.drop_table('assignedcenter')
    # ### end Alembic commands ###
