"""empty message

Revision ID: a3e07b23f0e2
Revises: 3a8751b7d495
Create Date: 2019-05-20 11:28:28.410702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e07b23f0e2'
down_revision = '3a8751b7d495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assignedcenter_evacuees_id_fkey', 'assignedcenter', type_='foreignkey')
    op.drop_column('assignedcenter', 'evacuees_id')
    op.add_column('evacuees', sa.Column('center_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'evacuees', 'distcenter', ['center_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evacuees', type_='foreignkey')
    op.drop_column('evacuees', 'center_id')
    op.add_column('assignedcenter', sa.Column('evacuees_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('assignedcenter_evacuees_id_fkey', 'assignedcenter', 'evacuees', ['evacuees_id'], ['id'])
    # ### end Alembic commands ###
