"""empty message

Revision ID: a5850917324f
Revises: a38ad82bf991
Create Date: 2019-04-14 14:44:48.982905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5850917324f'
down_revision = 'a38ad82bf991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('useradmin_role_key', 'useradmin', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('useradmin_role_key', 'useradmin', ['role'])
    # ### end Alembic commands ###
