"""empty message

Revision ID: aa65086490f4
Revises: f3d34d573f7a
Create Date: 2019-04-24 18:33:42.119133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa65086490f4'
down_revision = 'f3d34d573f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evacuees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('home_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('date_of_reg', sa.String(length=300), nullable=False),
    sa.Column('gender', sa.String(length=300), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('religion', sa.String(length=300), nullable=False),
    sa.Column('civil_status', sa.String(length=300), nullable=False),
    sa.Column('educ_attainment', sa.String(length=300), nullable=False),
    sa.Column('occupation', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('home_id')
    )
    op.add_column('distcenter', sa.Column('public_id', sa.String(length=300), nullable=False))
    op.drop_column('distcenter', 'publicid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distcenter', sa.Column('publicid', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.drop_column('distcenter', 'public_id')
    op.drop_table('evacuees')
    # ### end Alembic commands ###
