"""empty message

Revision ID: ab98a9bc1487
Revises: bbda934e1a46
Create Date: 2020-01-17 01:43:36.150279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab98a9bc1487'
down_revision = 'bbda934e1a46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manage',
    sa.Column('center_id', sa.String(length=300), nullable=True),
    sa.Column('acc_id', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['acc_id'], ['account.public_id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['distcenter.public_id'], )
    )
    op.add_column('evacuees', sa.Column('center_id', sa.String(length=300), nullable=True))
    op.create_foreign_key(None, 'evacuees', 'distcenter', ['center_id'], ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evacuees', type_='foreignkey')
    op.drop_column('evacuees', 'center_id')
    op.drop_table('manage')
    # ### end Alembic commands ###
