"""empty message

Revision ID: afdd470dceaf
Revises: de70d3390c5a
Create Date: 2019-05-22 22:01:50.646837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afdd470dceaf'
down_revision = 'de70d3390c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statisticsfemale',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grade_schooler', sa.Integer(), nullable=True),
    sa.Column('teens', sa.Integer(), nullable=True),
    sa.Column('young_adult', sa.Integer(), nullable=True),
    sa.Column('adult', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statisticsmale',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grade_schooler', sa.Integer(), nullable=True),
    sa.Column('teens', sa.Integer(), nullable=True),
    sa.Column('young_adult', sa.Integer(), nullable=True),
    sa.Column('adult', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statisticsmale')
    op.drop_table('statisticsfemale')
    # ### end Alembic commands ###
