"""empty message

Revision ID: b3b39523685d
Revises: 5f7ac7d35ce8
Create Date: 2019-05-19 22:24:09.671092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b39523685d'
down_revision = '5f7ac7d35ce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignedcenter', sa.Column('center_public_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assignedcenter', 'distcenter', ['center_public_id'], ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignedcenter', type_='foreignkey')
    op.drop_column('assignedcenter', 'center_public_id')
    # ### end Alembic commands ###
