"""empty message

Revision ID: b4c185a5f9e8
Revises: ab98a9bc1487
Create Date: 2020-01-17 10:01:55.059671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c185a5f9e8'
down_revision = 'ab98a9bc1487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('good_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('details', sa.String(length=300), nullable=True),
    sa.Column('public_id', sa.String(length=300), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('received_date', sa.String(length=300), nullable=False),
    sa.Column('distribute_date', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('center_id', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['distcenter.public_id'], ),
    sa.ForeignKeyConstraint(['type'], ['goods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    op.drop_table('good_type')
    # ### end Alembic commands ###
