"""empty message

Revision ID: b590450491b1
Revises: d53bc27aa7c8
Create Date: 2019-05-20 10:13:12.226276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b590450491b1'
down_revision = 'd53bc27aa7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependents', sa.Column('username', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'dependents', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dependents', type_='unique')
    op.drop_column('dependents', 'username')
    # ### end Alembic commands ###
