"""empty message

Revision ID: b69c6a1a978f
Revises: 6164691c68b4
Create Date: 2019-04-30 13:11:30.919560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b69c6a1a978f'
down_revision = '6164691c68b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('useradmin_first_name_key', 'useradmin', type_='unique')
    op.drop_constraint('useradmin_last_name_key', 'useradmin', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('useradmin_last_name_key', 'useradmin', ['last_name'])
    op.create_unique_constraint('useradmin_first_name_key', 'useradmin', ['first_name'])
    # ### end Alembic commands ###
