"""empty message

Revision ID: bef3d75acba4
Revises: 35939dc10c2e
Create Date: 2019-05-03 10:15:35.014000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef3d75acba4'
down_revision = '35939dc10c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dependents_id', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=300), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('educ_attainment', sa.String(length=300), nullable=False),
    sa.Column('occupation', sa.String(length=300), nullable=False),
    sa.Column('homeOwner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['homeOwner_id'], ['evacuees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dependents_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependents')
    # ### end Alembic commands ###
