"""empty message

Revision ID: cbda63a67677
Revises: cfd39818ad6a
Create Date: 2019-08-08 06:20:55.461200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbda63a67677'
down_revision = 'cfd39818ad6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('household',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('public_id', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('useradmin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('pass_hash', sa.String(length=100), nullable=True),
    sa.Column('img', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('usermobile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('pass_hash', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('contact_number', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('first_name'),
    sa.UniqueConstraint('last_name'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('distcenter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=300), nullable=False),
    sa.Column('managed_by', sa.String(length=100), nullable=True),
    sa.Column('img', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['managed_by'], ['useradmin.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('evacuees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('home_id', sa.String(length=100), nullable=True),
    sa.Column('is_house_leader', sa.Boolean(), nullable=True),
    sa.Column('public_id', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('date_of_reg', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.String(length=300), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('religion', sa.String(length=300), nullable=False),
    sa.Column('civil_status', sa.String(length=300), nullable=False),
    sa.Column('educ_attainment', sa.String(length=300), nullable=False),
    sa.Column('occupation', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['home_id'], ['household.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.String(length=100), nullable=True),
    sa.Column('received_date', sa.String(length=300), nullable=False),
    sa.Column('received_from', sa.String(length=300), nullable=False),
    sa.Column('distribute_date', sa.String(length=300), nullable=True),
    sa.Column('expiry', sa.String(length=300), nullable=True),
    sa.Column('size', sa.String(length=5), nullable=False),
    sa.Column('clothing_type', sa.String(length=300), nullable=False),
    sa.Column('condition', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['distcenter.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    op.drop_table('evacuees')
    op.drop_table('distcenter')
    op.drop_table('usermobile')
    op.drop_table('useradmin')
    op.drop_table('household')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
