"""empty message

Revision ID: d12025dd975b
Revises: b4c185a5f9e8
Create Date: 2020-01-17 10:03:27.002979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12025dd975b'
down_revision = 'b4c185a5f9e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('goods_type_fkey', 'goods', type_='foreignkey')
    op.create_foreign_key(None, 'goods', 'good_type', ['type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goods', type_='foreignkey')
    op.create_foreign_key('goods_type_fkey', 'goods', 'goods', ['type'], ['id'])
    # ### end Alembic commands ###
