"""empty message

Revision ID: d53bc27aa7c8
Revises: 1092f1c3e3a6
Create Date: 2019-05-20 07:09:55.695604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53bc27aa7c8'
down_revision = '1092f1c3e3a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignedcenter', sa.Column('dependents_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assignedcenter', 'dependents', ['dependents_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignedcenter', type_='foreignkey')
    op.drop_column('assignedcenter', 'dependents_id')
    # ### end Alembic commands ###
