"""empty message

Revision ID: dcdcafeefc91
Revises: a3e07b23f0e2
Create Date: 2019-05-20 15:59:17.462216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcdcafeefc91'
down_revision = 'a3e07b23f0e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dependents_username_key', 'dependents', type_='unique')
    op.drop_column('dependents', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependents', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint('dependents_username_key', 'dependents', ['username'])
    # ### end Alembic commands ###
