"""empty message

Revision ID: de70d3390c5a
Revises: dcdcafeefc91
Create Date: 2019-05-20 16:08:19.443464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de70d3390c5a'
down_revision = 'dcdcafeefc91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dependents_home_id_fkey', 'dependents', type_='foreignkey')
    op.create_foreign_key(None, 'dependents', 'evacuees', ['home_id'], ['home_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dependents', type_='foreignkey')
    op.create_foreign_key('dependents_home_id_fkey', 'dependents', 'evacuees', ['home_id'], ['id'])
    # ### end Alembic commands ###
