"""empty message

Revision ID: f4d1f583ea2b
Revises: df5a9d5ff9bd
Create Date: 2019-05-19 16:51:04.142089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d1f583ea2b'
down_revision = 'df5a9d5ff9bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distcenter', sa.Column('marker', sa.Integer(), autoincrement=True, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distcenter', 'marker')
    # ### end Alembic commands ###
