"""empty message

Revision ID: f71ca29e63a1
Revises: e0bfc3d03fb3
Create Date: 2019-05-23 17:18:55.227655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71ca29e63a1'
down_revision = 'e0bfc3d03fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distcenter', sa.Column('img', sa.String(length=300), nullable=True))
    op.add_column('useradmin', sa.Column('img', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('useradmin', 'img')
    op.drop_column('distcenter', 'img')
    # ### end Alembic commands ###
